from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 708)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/book_shop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
                                 "QWidget {\n"
                                 "    background-color: qlineargradient(spread:pad, x1:0.264, y1:0, x2:0.294, y2:1, stop:0 rgba(30, 33, 61, 255), stop:0.497512 rgba(20, 23, 96, 255), stop:1 rgba(30, 33, 61, 255));\n"
                                 "    color: white;\n"
                                 "    font-family: Rubick;\n"
                                 "    font-size: 12pt;\n"
                                 "    font-weight: 600;\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "\n"
                                 "QFrame{\n"
                                 "    background-color: rgba(0,0,0,0);\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit{\n"
                                 "    background-color: rgba(0,0,0,0);\n"
                                 "}\n"
                                 "\n"
                                 "QToolTip {\n"
                                 "    font-family: Rubick;\n"
                                 "    font-size: 12pt;\n"
                                 "    color:white; \n"
                                 "    padding:2px;\n"
                                 "    border-width:2px;\n"
                                 "    border-style:solid;\n"
                                 "    border-radius:20px;\n"
                                 "    background-color: rgb(30, 33, 61);\n"
                                 "    border: 1px solid white;\n"
                                 "    border-radius: 7px;\n"
                                 "    overflow:hidden;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit {\n"
                                 "    background-color: rgb(255, 255, 255);\n"
                                 "    border: 1px solid #54026E;\n"
                                 "    border-radius: 4px;\n"
                                 "    color: rgb(30, 33, 61);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "    background-color: transparent;\n"
                                 "    border: none;\n"
                                 "    border-radius: 7px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: rgb(66, 60, 99);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgb(28, 28, 28);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar:horizontal {\n"
                                 "    border: 2px solid rrgb(26, 22, 42);\n"
                                 "    background: rgb(66, 60, 99);\n"
                                 "    height: 15px;\n"
                                 "    margin: 0px 20px 0 20px;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::handle:horizontal {\n"
                                 "    background-color: rgb(26, 22, 42);\n"
                                 "    min-width: 22px;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::add-line:horizontal {\n"
                                 "    image: url(:/newPrefix/icon2/right_arrow (2).png);\n"
                                 "    border: 2px solid rgb(66, 60, 99);\n"
                                 "    background: rgb(26, 22, 42);\n"
                                 "    width: 20px;\n"
                                 "    subcontrol-position: right;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::sub-line:horizontal {\n"
                                 "    border: 2px solid rgb(66, 60, 99);\n"
                                 "    background: rgb(26, 22, 42);\n"
                                 "    width: 20px;\n"
                                 "    subcontrol-position: left;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "    image: url(:/newPrefix/icon2/left_arrow.png)\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar:vertical {\n"
                                 "    border: 2px solid rrgb(26, 22, 42);\n"
                                 "    background: rgb(66, 60, 99);\n"
                                 "    width: 15px;\n"
                                 "    width: 18px;\n"
                                 "    margin: 20px 0 20px 0;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::handle:vertical {\n"
                                 "    background-color: rgb(26, 22, 42);;\n"
                                 "    min-width: 22px;\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::add-line:vertical {\n"
                                 "    image: url(:/newPrefix/icon2/right_arrow (2).png);\n"
                                 "    border: 2px solid rgb(66, 60, 99);\n"
                                 "    background: rgb(26, 22, 42);\n"
                                 "    height: 20px;\n"
                                 "    subcontrol-position: bottom;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "    image: url(:/newPrefix/icon2/bot_arrow.png);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::sub-line:vertical {\n"
                                 "    border: 2px solid rgb(66, 60, 99);\n"
                                 "    background: rgb(26, 22, 42);\n"
                                 "    height: 20px;\n"
                                 "    subcontrol-position: top;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "    image: url(:/newPrefix/icon2/up_arrow.png);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::handle:hover {\n"
                                 "    background: rgb(66, 60, 99);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::handle:pressed {\n"
                                 "    background-color: rgb(28, 28, 28);\n"
                                 "}\n"
                                 "\n"
                                 "QScrollBar::add-page, QScrollBar::sub-page {\n"
                                 "    background: rgb(138, 130, 179)\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:disabled {\n"
                                 "    background-color: rgba(144,144,144);\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_status_mw = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_status_mw.sizePolicy().hasHeightForWidth())
        self.frame_status_mw.setSizePolicy(sizePolicy)
        self.frame_status_mw.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_status_mw.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status_mw.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status_mw.setObjectName("frame_status_mw")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_status_mw)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_icnon_status_mw = QtWidgets.QLabel(self.frame_status_mw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icnon_status_mw.sizePolicy().hasHeightForWidth())
        self.label_icnon_status_mw.setSizePolicy(sizePolicy)
        self.label_icnon_status_mw.setMinimumSize(QtCore.QSize(40, 30))
        self.label_icnon_status_mw.setStyleSheet("image: url(:/newPrefix/icon2/searsh.png);")
        self.label_icnon_status_mw.setText("")
        self.label_icnon_status_mw.setObjectName("label_icnon_status_mw")
        self.horizontalLayout.addWidget(self.label_icnon_status_mw, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_name_status_mw = QtWidgets.QLabel(self.frame_status_mw)
        self.label_name_status_mw.setObjectName("label_name_status_mw")
        self.horizontalLayout.addWidget(self.label_name_status_mw, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_fold__status_mw = QtWidgets.QPushButton(self.frame_status_mw)
        self.pushButton_fold__status_mw.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton_fold__status_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_fold__status_mw.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/bot_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_fold__status_mw.setIcon(icon1)
        self.pushButton_fold__status_mw.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_fold__status_mw.setObjectName("pushButton_fold__status_mw")
        self.horizontalLayout.addWidget(self.pushButton_fold__status_mw, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.pushButton_expand_status_mw = QtWidgets.QPushButton(self.frame_status_mw)
        self.pushButton_expand_status_mw.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton_expand_status_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_expand_status_mw.setStyleSheet("")
        self.pushButton_expand_status_mw.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_expand_status_mw.setIcon(icon2)
        self.pushButton_expand_status_mw.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_expand_status_mw.setObjectName("pushButton_expand_status_mw")
        self.horizontalLayout.addWidget(self.pushButton_expand_status_mw, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.pushButton_close_status_mw = QtWidgets.QPushButton(self.frame_status_mw)
        self.pushButton_close_status_mw.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton_close_status_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_status_mw.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_status_mw.setIcon(icon3)
        self.pushButton_close_status_mw.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_close_status_mw.setObjectName("pushButton_close_status_mw")
        self.horizontalLayout.addWidget(self.pushButton_close_status_mw, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.frame_status_mw, 0, 0, 1, 6)
        self.frame_menu_mw = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu_mw.sizePolicy().hasHeightForWidth())
        self.frame_menu_mw.setSizePolicy(sizePolicy)
        self.frame_menu_mw.setMinimumSize(QtCore.QSize(235, 500))
        self.frame_menu_mw.setStyleSheet("QFrame{\n"
                                         "    border: 1px solid #54026E;\n"
                                         "    border-radius: 4px;\n"
                                         "}")
        self.frame_menu_mw.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu_mw.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu_mw.setObjectName("frame_menu_mw")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_menu_mw)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_profile_user_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_profile_user_mw.setEnabled(True)
        self.pushButton_profile_user_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_profile_user_mw.setIcon(icon4)
        self.pushButton_profile_user_mw.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_profile_user_mw.setObjectName("pushButton_profile_user_mw")
        self.verticalLayout_3.addWidget(self.pushButton_profile_user_mw)
        self.pushButton_main_menu_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_main_menu_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/menu_cube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_main_menu_mw.setIcon(icon5)
        self.pushButton_main_menu_mw.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_main_menu_mw.setCheckable(False)
        self.pushButton_main_menu_mw.setObjectName("pushButton_main_menu_mw")
        self.verticalLayout_3.addWidget(self.pushButton_main_menu_mw)
        self.pushButton_setting_user_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_setting_user_mw.setMinimumSize(QtCore.QSize(170, 0))
        self.pushButton_setting_user_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_user_mw.setIcon(icon6)
        self.pushButton_setting_user_mw.setIconSize(QtCore.QSize(30, 40))
        self.pushButton_setting_user_mw.setObjectName("pushButton_setting_user_mw")
        self.verticalLayout_3.addWidget(self.pushButton_setting_user_mw)
        self.pushButton_reference_user_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_reference_user_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reference_user_mw.setIcon(icon7)
        self.pushButton_reference_user_mw.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_reference_user_mw.setCheckable(False)
        self.pushButton_reference_user_mw.setObjectName("pushButton_reference_user_mw")
        self.verticalLayout_3.addWidget(self.pushButton_reference_user_mw)
        self.pushButton_help_user_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_help_user_mw.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton_help_user_mw.setToolTipDuration(-1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_help_user_mw.setIcon(icon8)
        self.pushButton_help_user_mw.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_help_user_mw.setCheckable(False)
        self.pushButton_help_user_mw.setObjectName("pushButton_help_user_mw")
        self.verticalLayout_3.addWidget(self.pushButton_help_user_mw)
        self.pushButton_all_bookwark_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_all_bookwark_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_all_bookwark_mw.setIcon(icon9)
        self.pushButton_all_bookwark_mw.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_all_bookwark_mw.setCheckable(False)
        self.pushButton_all_bookwark_mw.setObjectName("pushButton_all_bookwark_mw")
        self.verticalLayout_3.addWidget(self.pushButton_all_bookwark_mw)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton_fold_user_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_fold_user_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/right_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_fold_user_mw.setIcon(icon10)
        self.pushButton_fold_user_mw.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_fold_user_mw.setObjectName("pushButton_fold_user_mw")
        self.verticalLayout_3.addWidget(self.pushButton_fold_user_mw)
        self.pushButton_exit_user_mw = QtWidgets.QPushButton(self.frame_menu_mw)
        self.pushButton_exit_user_mw.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit_user_mw.setIcon(icon11)
        self.pushButton_exit_user_mw.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_exit_user_mw.setObjectName("pushButton_exit_user_mw")
        self.verticalLayout_3.addWidget(self.pushButton_exit_user_mw)
        self.gridLayout.addWidget(self.frame_menu_mw, 2, 5, 2, 1)
        self.frame_all_book = QtWidgets.QFrame(self.centralwidget)
        self.frame_all_book.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_all_book.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_all_book.setObjectName("frame_all_book")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_all_book)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_search_ab = QtWidgets.QFrame(self.frame_all_book)
        self.frame_search_ab.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search_ab.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search_ab.setObjectName("frame_search_ab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_search_ab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.icon_search_ab = QtWidgets.QLabel(self.frame_search_ab)
        self.icon_search_ab.setMinimumSize(QtCore.QSize(40, 30))
        self.icon_search_ab.setMaximumSize(QtCore.QSize(40, 30))
        self.icon_search_ab.setStyleSheet("image: url(:/newPrefix/icon2/searsh.png);")
        self.icon_search_ab.setText("")
        self.icon_search_ab.setObjectName("icon_search_ab")
        self.horizontalLayout_6.addWidget(self.icon_search_ab)
        self.lineEdit_search_ab = QtWidgets.QLineEdit(self.frame_search_ab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search_ab.sizePolicy().hasHeightForWidth())
        self.lineEdit_search_ab.setSizePolicy(sizePolicy)
        self.lineEdit_search_ab.setMinimumSize(QtCore.QSize(400, 25))
        self.lineEdit_search_ab.setStyleSheet("")
        self.lineEdit_search_ab.setObjectName("lineEdit_search_ab")
        self.horizontalLayout_6.addWidget(self.lineEdit_search_ab, 0, QtCore.Qt.AlignVCenter)
        self.pushButton_search = QtWidgets.QPushButton(self.frame_search_ab)
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_search.setIconSize(QtCore.QSize(40, 60))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_6.addWidget(self.pushButton_search)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_sort = QtWidgets.QPushButton(self.frame_search_ab)
        self.pushButton_sort.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_sort.setIconSize(QtCore.QSize(40, 60))
        self.pushButton_sort.setObjectName("pushButton_sort")
        self.horizontalLayout_6.addWidget(self.pushButton_sort)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_menu_ab = QtWidgets.QPushButton(self.frame_search_ab)
        self.pushButton_menu_ab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_menu_ab.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_menu_ab.setIcon(icon12)
        self.pushButton_menu_ab.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_menu_ab.setObjectName("pushButton_menu_ab")
        self.horizontalLayout_6.addWidget(self.pushButton_menu_ab, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_search_ab, 0, QtCore.Qt.AlignTop)
        self.scrollArea_main_ab = QtWidgets.QScrollArea(self.frame_all_book)
        self.scrollArea_main_ab.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_main_ab.setStyleSheet("\n"
                                              "QPushButton {\n"
                                              "    background-color: transparent;\n"
                                              "    border: none;\n"
                                              "    border-radius: 7px;\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:hover {\n"
                                              "    background-color: rgb(66, 60, 99);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed {\n"
                                              "    background-color: rgb(28, 28, 28);\n"
                                              "};\n"
                                              "\n"
                                              "background-color: rgba(0,0,0,0);")
        self.scrollArea_main_ab.setWidgetResizable(True)
        self.scrollArea_main_ab.setObjectName("scrollArea_main_ab")
        self.scrollAreaWidget_ab = QtWidgets.QWidget()
        self.scrollAreaWidget_ab.setGeometry(QtCore.QRect(0, 0, 807, 549))
        self.scrollAreaWidget_ab.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollAreaWidget_ab.setStyleSheet("")
        self.scrollAreaWidget_ab.setObjectName("scrollAreaWidget_ab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidget_ab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_search = QtWidgets.QFrame(self.scrollAreaWidget_ab)
        self.frame_search.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_search.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_search.setStyleSheet("QFrame {\n"
                                        "    border: 1px solid #54026E;\n"
                                        "    border-radius: 4px;\n"
                                        "}\n"
                                        "QLabel {\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "")
        self.frame_search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search.setObjectName("frame_search")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_search)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_close_status_mw_2 = QtWidgets.QPushButton(self.frame_search)
        self.pushButton_close_status_mw_2.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton_close_status_mw_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_status_mw_2.setText("")
        self.pushButton_close_status_mw_2.setIcon(icon3)
        self.pushButton_close_status_mw_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_close_status_mw_2.setObjectName("pushButton_close_status_mw_2")
        self.gridLayout_8.addWidget(self.pushButton_close_status_mw_2, 0, 3, 1, 1,
                                    QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.frame_button = QtWidgets.QFrame(self.frame_search)
        self.frame_button.setStyleSheet("border: 0px;\n"
                                        "")
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_button)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_search_sort = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_search_sort.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_search_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_search_sort.setObjectName("pushButton_search_sort")
        self.horizontalLayout_7.addWidget(self.pushButton_search_sort)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.pushButton_clear = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_7.addWidget(self.pushButton_clear)
        self.gridLayout_8.addWidget(self.frame_button, 1, 3, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.frame_categories = QtWidgets.QFrame(self.frame_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_categories.sizePolicy().hasHeightForWidth())
        self.frame_categories.setSizePolicy(sizePolicy)
        self.frame_categories.setStyleSheet("border: 0px;\n"
                                            "")
        self.frame_categories.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_categories.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_categories.setObjectName("frame_categories")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_categories)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_search_avtor = QtWidgets.QFrame(self.frame_categories)
        self.frame_search_avtor.setStyleSheet("border: 0px;\n"
                                              "\n"
                                              "")
        self.frame_search_avtor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search_avtor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search_avtor.setObjectName("frame_search_avtor")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_search_avtor)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_search_author = QtWidgets.QLabel(self.frame_search_avtor)
        self.label_search_author.setObjectName("label_search_author")
        self.verticalLayout_7.addWidget(self.label_search_author)
        self.lineEdit_author = QtWidgets.QLineEdit(self.frame_search_avtor)
        self.lineEdit_author.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_author.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.verticalLayout_7.addWidget(self.lineEdit_author, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_10.addWidget(self.frame_search_avtor)
        self.frame_search_publication = QtWidgets.QFrame(self.frame_categories)
        self.frame_search_publication.setStyleSheet("border: 0px;\n"
                                                    "")
        self.frame_search_publication.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search_publication.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search_publication.setObjectName("frame_search_publication")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_search_publication)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_search_publisher = QtWidgets.QLabel(self.frame_search_publication)
        self.label_search_publisher.setObjectName("label_search_publisher")
        self.verticalLayout_8.addWidget(self.label_search_publisher)
        self.lineEdit_publisher = QtWidgets.QLineEdit(self.frame_search_publication)
        self.lineEdit_publisher.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_publisher.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_publisher.setObjectName("lineEdit_publisher")
        self.verticalLayout_8.addWidget(self.lineEdit_publisher, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_10.addWidget(self.frame_search_publication)
        self.frame_search_price = QtWidgets.QFrame(self.frame_categories)
        self.frame_search_price.setStyleSheet("border: 0px;\n"
                                              "")
        self.frame_search_price.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search_price.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search_price.setObjectName("frame_search_price")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_search_price)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.spinBox_from = QtWidgets.QSpinBox(self.frame_search_price)
        self.spinBox_from.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_from.setSuffix("")
        self.spinBox_from.setMaximum(99999999)
        self.spinBox_from.setObjectName("spinBox_from")
        self.gridLayout_10.addWidget(self.spinBox_from, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 1, 1, 1, 1)
        self.spinBox_to = QtWidgets.QSpinBox(self.frame_search_price)
        self.spinBox_to.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_to.setSuffix("")
        self.spinBox_to.setMaximum(99999999)
        self.spinBox_to.setProperty("value", 96799)
        self.spinBox_to.setDisplayIntegerBase(10)
        self.spinBox_to.setObjectName("spinBox_to")
        self.gridLayout_10.addWidget(self.spinBox_to, 1, 2, 1, 1)
        self.label_search_price = QtWidgets.QLabel(self.frame_search_price)
        self.label_search_price.setStyleSheet("border: 0px;\n"
                                              "")
        self.label_search_price.setObjectName("label_search_price")
        self.gridLayout_10.addWidget(self.label_search_price, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_search_price, 0, QtCore.Qt.AlignLeft)
        self.frame_date = QtWidgets.QFrame(self.frame_categories)
        self.frame_date.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_date.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_date.setObjectName("frame_date")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_date)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.dateEdit_second = QtWidgets.QDateEdit(self.frame_date)
        self.dateEdit_second.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.dateEdit_second.setDate(QtCore.QDate(2023, 1, 1))
        self.dateEdit_second.setObjectName("dateEdit_second")
        self.gridLayout_12.addWidget(self.dateEdit_second, 3, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.dateEdit_first = QtWidgets.QDateEdit(self.frame_date)
        self.dateEdit_first.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.dateEdit_first.setDate(QtCore.QDate(1900, 1, 1))
        self.dateEdit_first.setObjectName("dateEdit_first")
        self.gridLayout_12.addWidget(self.dateEdit_first, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_to = QtWidgets.QLabel(self.frame_date)
        self.label_to.setObjectName("label_to")
        self.gridLayout_12.addWidget(self.label_to, 2, 2, 1, 1)
        self.label_from = QtWidgets.QLabel(self.frame_date)
        self.label_from.setObjectName("label_from")
        self.gridLayout_12.addWidget(self.label_from, 2, 0, 1, 1)
        self.label_date = QtWidgets.QLabel(self.frame_date)
        self.label_date.setObjectName("label_date")
        self.gridLayout_12.addWidget(self.label_date, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 3, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_date, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_8.addWidget(self.frame_categories, 0, 2, 2, 1)
        self.gridLayout_3.addWidget(self.frame_search, 1, 0, 1, 2)
        self.all_book = QtWidgets.QFrame(self.scrollAreaWidget_ab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_book.sizePolicy().hasHeightForWidth())
        self.all_book.setSizePolicy(sizePolicy)
        self.all_book.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.all_book.setFrameShadow(QtWidgets.QFrame.Raised)
        self.all_book.setObjectName("all_book")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.all_book)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_3.addWidget(self.all_book, 3, 0, 1, 2)
        self.label_you_mean = QtWidgets.QLabel(self.scrollAreaWidget_ab)
        self.label_you_mean.setMouseTracking(False)
        self.label_you_mean.setObjectName("label_you_mean")
        self.gridLayout_3.addWidget(self.label_you_mean, 2, 0, 1, 1)
        self.scrollArea_main_ab.setWidget(self.scrollAreaWidget_ab)
        self.verticalLayout_2.addWidget(self.scrollArea_main_ab)
        self.pushButton_reset = QtWidgets.QPushButton(self.frame_all_book)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_2.addWidget(self.pushButton_reset, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.frame_all_book, 2, 3, 1, 1)
        self.frame_buy_book = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buy_book.sizePolicy().hasHeightForWidth())
        self.frame_buy_book.setSizePolicy(sizePolicy)
        self.frame_buy_book.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_buy_book.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_buy_book.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buy_book.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_buy_book.setObjectName("frame_buy_book")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_buy_book)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.frame_buy_book)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 2, 1, 1)
        self.pushButton_back_bb = QtWidgets.QPushButton(self.frame_buy_book)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_back_bb.sizePolicy().hasHeightForWidth())
        self.pushButton_back_bb.setSizePolicy(sizePolicy)
        self.pushButton_back_bb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back_bb.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back_bb.setIcon(icon13)
        self.pushButton_back_bb.setIconSize(QtCore.QSize(50, 60))
        self.pushButton_back_bb.setObjectName("pushButton_back_bb")
        self.gridLayout_7.addWidget(self.pushButton_back_bb, 0, 0, 1, 1)
        self.frame_info_bb = QtWidgets.QFrame(self.frame_buy_book)
        self.frame_info_bb.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_info_bb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info_bb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info_bb.setObjectName("frame_info_bb")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_info_bb)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_info_price_bb = QtWidgets.QFrame(self.frame_info_bb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info_price_bb.sizePolicy().hasHeightForWidth())
        self.frame_info_price_bb.setSizePolicy(sizePolicy)
        self.frame_info_price_bb.setStyleSheet("QFrame {\n"
                                               "    border: 1px solid #54026E;\n"
                                               "    border-radius: 4px;\n"
                                               "}\n"
                                               "QLabel {\n"
                                               "    border: 0px solid;\n"
                                               "}\n"
                                               "")
        self.frame_info_price_bb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info_price_bb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info_price_bb.setObjectName("frame_info_price_bb")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_info_price_bb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_results_bb = QtWidgets.QLabel(self.frame_info_price_bb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_results_bb.sizePolicy().hasHeightForWidth())
        self.label_results_bb.setSizePolicy(sizePolicy)
        self.label_results_bb.setObjectName("label_results_bb")
        self.verticalLayout.addWidget(self.label_results_bb, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.label_price_bb = QtWidgets.QLabel(self.frame_info_price_bb)
        self.label_price_bb.setObjectName("label_price_bb")
        self.verticalLayout.addWidget(self.label_price_bb, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        spacerItem7 = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.pushButton_buy_bb = QtWidgets.QPushButton(self.frame_info_price_bb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_buy_bb.sizePolicy().hasHeightForWidth())
        self.pushButton_buy_bb.setSizePolicy(sizePolicy)
        self.pushButton_buy_bb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_buy_bb.setStyleSheet("QPushButton {\n"
                                             "    background-color: rgb(104, 194, 104);\n"
                                             "    border: none;\n"
                                             "    border-radius: 7px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: rgb(119, 221, 119);\n"
                                             "}\n"
                                             "QPushButton:pressed {\n"
                                             "    background-color: rgb(19, 136, 8);\n"
                                             "}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/buy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_buy_bb.setIcon(icon14)
        self.pushButton_buy_bb.setIconSize(QtCore.QSize(40, 29))
        self.pushButton_buy_bb.setObjectName("pushButton_buy_bb")
        self.verticalLayout.addWidget(self.pushButton_buy_bb, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.verticalLayout_6.addWidget(self.frame_info_price_bb, 0, QtCore.Qt.AlignBottom)
        self.gridLayout_7.addWidget(self.frame_info_bb, 1, 4, 1, 1)
        self.scrollArea_bb = QtWidgets.QScrollArea(self.frame_buy_book)
        self.scrollArea_bb.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.scrollArea_bb.setWidgetResizable(True)
        self.scrollArea_bb.setObjectName("scrollArea_bb")
        self.scrollAreaWidget_bb = QtWidgets.QWidget()
        self.scrollAreaWidget_bb.setGeometry(QtCore.QRect(0, 0, 194, 596))
        self.scrollAreaWidget_bb.setObjectName("scrollAreaWidget_bb")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidget_bb)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_bb.setWidget(self.scrollAreaWidget_bb)
        self.gridLayout_7.addWidget(self.scrollArea_bb, 1, 2, 1, 2)
        self.frame_infouser_bb = QtWidgets.QFrame(self.frame_buy_book)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_infouser_bb.sizePolicy().hasHeightForWidth())
        self.frame_infouser_bb.setSizePolicy(sizePolicy)
        self.frame_infouser_bb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infouser_bb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infouser_bb.setObjectName("frame_infouser_bb")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_infouser_bb)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.avatar_img = QtWidgets.QLabel(self.frame_infouser_bb)
        self.avatar_img.setText("")
        self.avatar_img.setPixmap(QtGui.QPixmap(":/newPrefix/icon2/user.png"))
        self.avatar_img.setObjectName("avatar_img")
        self.horizontalLayout_5.addWidget(self.avatar_img, 0, QtCore.Qt.AlignRight)
        self.name_user = QtWidgets.QLabel(self.frame_infouser_bb)
        self.name_user.setObjectName("name_user")
        self.horizontalLayout_5.addWidget(self.name_user, 0, QtCore.Qt.AlignRight)
        spacerItem8 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.pushButton_menu_bb = QtWidgets.QPushButton(self.frame_infouser_bb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_menu_bb.sizePolicy().hasHeightForWidth())
        self.pushButton_menu_bb.setSizePolicy(sizePolicy)
        self.pushButton_menu_bb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_menu_bb.setText("")
        self.pushButton_menu_bb.setIcon(icon12)
        self.pushButton_menu_bb.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_menu_bb.setObjectName("pushButton_menu_bb")
        self.horizontalLayout_5.addWidget(self.pushButton_menu_bb)
        self.gridLayout_7.addWidget(self.frame_infouser_bb, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.frame_buy_book, 2, 1, 1, 1)
        self.frame_info_book = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_info_book.sizePolicy().hasHeightForWidth())
        self.frame_info_book.setSizePolicy(sizePolicy)
        self.frame_info_book.setStyleSheet("")
        self.frame_info_book.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info_book.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info_book.setObjectName("frame_info_book")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_info_book)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_header_ib = QtWidgets.QFrame(self.frame_info_book)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_header_ib.sizePolicy().hasHeightForWidth())
        self.frame_header_ib.setSizePolicy(sizePolicy)
        self.frame_header_ib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_header_ib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header_ib.setObjectName("frame_header_ib")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_header_ib)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_back_ib = QtWidgets.QPushButton(self.frame_header_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_back_ib.sizePolicy().hasHeightForWidth())
        self.pushButton_back_ib.setSizePolicy(sizePolicy)
        self.pushButton_back_ib.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back_ib.setText("")
        self.pushButton_back_ib.setIcon(icon13)
        self.pushButton_back_ib.setIconSize(QtCore.QSize(50, 60))
        self.pushButton_back_ib.setObjectName("pushButton_back_ib")
        self.horizontalLayout_2.addWidget(self.pushButton_back_ib, 0, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.pushButton_menu_ib = QtWidgets.QPushButton(self.frame_header_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_menu_ib.sizePolicy().hasHeightForWidth())
        self.pushButton_menu_ib.setSizePolicy(sizePolicy)
        self.pushButton_menu_ib.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_menu_ib.setText("")
        self.pushButton_menu_ib.setIcon(icon12)
        self.pushButton_menu_ib.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_menu_ib.setObjectName("pushButton_menu_ib")
        self.horizontalLayout_2.addWidget(self.pushButton_menu_ib, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.frame_header_ib, 1, 0, 1, 2, QtCore.Qt.AlignTop)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_info_book)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 668, 711))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_buy_ib = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buy_ib.sizePolicy().hasHeightForWidth())
        self.frame_buy_ib.setSizePolicy(sizePolicy)
        self.frame_buy_ib.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_buy_ib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buy_ib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buy_ib.setObjectName("frame_buy_ib")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_buy_ib)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.condition_ib = QtWidgets.QLabel(self.frame_buy_ib)
        self.condition_ib.setObjectName("condition_ib")
        self.gridLayout_9.addWidget(self.condition_ib, 2, 0, 1, 1, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.frame_button_ib = QtWidgets.QFrame(self.frame_buy_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_button_ib.sizePolicy().hasHeightForWidth())
        self.frame_button_ib.setSizePolicy(sizePolicy)
        self.frame_button_ib.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_button_ib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_ib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_ib.setObjectName("frame_button_ib")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_button_ib)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_arrange_ib = QtWidgets.QPushButton(self.frame_button_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arrange_ib.sizePolicy().hasHeightForWidth())
        self.pushButton_arrange_ib.setSizePolicy(sizePolicy)
        self.pushButton_arrange_ib.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_arrange_ib.setStyleSheet("QPushButton {\n"
                                                 "    background-color: rgb(119, 221, 119);\n"
                                                 "    border: none;\n"
                                                 "    border-radius: 7px;\n"
                                                 "}\n"
                                                 "QPushButton:hover {\n"
                                                 "    background-color: rgb(152, 255, 152);\n"
                                                 "}\n"
                                                 "QPushButton:pressed {\n"
                                                 "    background-color: rgb(19, 136, 8);\n"
                                                 "}\n"
                                                 "QPushButton:disabled {\n"
                                                 "    background-color: rgba(144,144,144);\n"
                                                 "}")
        self.pushButton_arrange_ib.setIcon(icon14)
        self.pushButton_arrange_ib.setIconSize(QtCore.QSize(40, 29))
        self.pushButton_arrange_ib.setDefault(False)
        self.pushButton_arrange_ib.setFlat(False)
        self.pushButton_arrange_ib.setObjectName("pushButton_arrange_ib")
        self.verticalLayout_9.addWidget(self.pushButton_arrange_ib, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.pushButton_bookmark_ib = QtWidgets.QPushButton(self.frame_button_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bookmark_ib.sizePolicy().hasHeightForWidth())
        self.pushButton_bookmark_ib.setSizePolicy(sizePolicy)
        self.pushButton_bookmark_ib.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_bookmark_ib.setStyleSheet("QPushButton {\n"
                                                  "    background-color: rgb(27, 169, 212);\n"
                                                  "    border: none;\n"
                                                  "    border-radius: 7px;\n"
                                                  "}\n"
                                                  "QPushButton:hover {\n"
                                                  "    \n"
                                                  "    background-color: rgb(31, 235, 249);\n"
                                                  "}\n"
                                                  "QPushButton:pressed {\n"
                                                  "    background-color: rgb(20, 131, 161);\n"
                                                  "}")
        self.pushButton_bookmark_ib.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/bookmark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bookmark_ib.setIcon(icon15)
        self.pushButton_bookmark_ib.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_bookmark_ib.setObjectName("pushButton_bookmark_ib")
        self.verticalLayout_9.addWidget(self.pushButton_bookmark_ib, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.gridLayout_9.addWidget(self.frame_button_ib, 1, 0, 1, 1)
        self.price_ib = QtWidgets.QLabel(self.frame_buy_ib)
        self.price_ib.setObjectName("price_ib")
        self.gridLayout_9.addWidget(self.price_ib, 0, 0, 1, 1, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignBottom)
        self.gridLayout_4.addWidget(self.frame_buy_ib, 2, 0, 1, 1, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.frame_allinfo_ib = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_allinfo_ib.sizePolicy().hasHeightForWidth())
        self.frame_allinfo_ib.setSizePolicy(sizePolicy)
        self.frame_allinfo_ib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_allinfo_ib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_allinfo_ib.setObjectName("frame_allinfo_ib")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_allinfo_ib)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 0, 1, 1, 1)
        self.age_restrictions_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.age_restrictions_ib.sizePolicy().hasHeightForWidth())
        self.age_restrictions_ib.setSizePolicy(sizePolicy)
        self.age_restrictions_ib.setObjectName("age_restrictions_ib")
        self.gridLayout_5.addWidget(self.age_restrictions_ib, 10, 2, 1, 1)
        self.ISBN_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ISBN_ib.sizePolicy().hasHeightForWidth())
        self.ISBN_ib.setSizePolicy(sizePolicy)
        self.ISBN_ib.setObjectName("ISBN_ib")
        self.gridLayout_5.addWidget(self.ISBN_ib, 3, 2, 1, 1)
        self.number_pages_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_pages_ib.sizePolicy().hasHeightForWidth())
        self.number_pages_ib.setSizePolicy(sizePolicy)
        self.number_pages_ib.setObjectName("number_pages_ib")
        self.gridLayout_5.addWidget(self.number_pages_ib, 5, 2, 1, 1)
        self.format_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.format_ib.sizePolicy().hasHeightForWidth())
        self.format_ib.setSizePolicy(sizePolicy)
        self.format_ib.setObjectName("format_ib")
        self.gridLayout_5.addWidget(self.format_ib, 6, 2, 1, 1)
        self.label5_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label5_ib.setObjectName("label5_ib")
        self.gridLayout_5.addWidget(self.label5_ib, 4, 0, 1, 1)
        self.publisher_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.publisher_ib.sizePolicy().hasHeightForWidth())
        self.publisher_ib.setSizePolicy(sizePolicy)
        self.publisher_ib.setObjectName("publisher_ib")
        self.gridLayout_5.addWidget(self.publisher_ib, 0, 2, 1, 1)
        self.label3_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label3_ib.setObjectName("label3_ib")
        self.gridLayout_5.addWidget(self.label3_ib, 2, 0, 1, 1)
        self.year_publication_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_publication_ib.sizePolicy().hasHeightForWidth())
        self.year_publication_ib.setSizePolicy(sizePolicy)
        self.year_publication_ib.setObjectName("year_publication_ib")
        self.gridLayout_5.addWidget(self.year_publication_ib, 2, 2, 1, 1)
        self.label8_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label8_ib.setObjectName("label8_ib")
        self.gridLayout_5.addWidget(self.label8_ib, 7, 0, 1, 1)
        self.label7_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label7_ib.setObjectName("label7_ib")
        self.gridLayout_5.addWidget(self.label7_ib, 6, 0, 1, 1)
        self.label6_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label6_ib.setObjectName("label6_ib")
        self.gridLayout_5.addWidget(self.label6_ib, 5, 0, 1, 1)
        self.label1_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label1_ib.setObjectName("label1_ib")
        self.gridLayout_5.addWidget(self.label1_ib, 0, 0, 1, 1)
        self.label10_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label10_ib.setObjectName("label10_ib")
        self.gridLayout_5.addWidget(self.label10_ib, 10, 0, 1, 1)
        self.label9_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label9_ib.setObjectName("label9_ib")
        self.gridLayout_5.addWidget(self.label9_ib, 9, 0, 1, 1)
        self.quantities_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantities_ib.sizePolicy().hasHeightForWidth())
        self.quantities_ib.setSizePolicy(sizePolicy)
        self.quantities_ib.setObjectName("quantities_ib")
        self.gridLayout_5.addWidget(self.quantities_ib, 11, 2, 1, 1)
        self.label2_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label2_ib.setObjectName("label2_ib")
        self.gridLayout_5.addWidget(self.label2_ib, 1, 0, 1, 1)
        self.series_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.series_ib.sizePolicy().hasHeightForWidth())
        self.series_ib.setSizePolicy(sizePolicy)
        self.series_ib.setObjectName("series_ib")
        self.gridLayout_5.addWidget(self.series_ib, 1, 2, 1, 1)
        self.label4_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label4_ib.setObjectName("label4_ib")
        self.gridLayout_5.addWidget(self.label4_ib, 3, 0, 1, 1)
        self.cove_type_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cove_type_ib.sizePolicy().hasHeightForWidth())
        self.cove_type_ib.setSizePolicy(sizePolicy)
        self.cove_type_ib.setObjectName("cove_type_ib")
        self.gridLayout_5.addWidget(self.cove_type_ib, 7, 2, 1, 1)
        self.weight_g_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight_g_ib.sizePolicy().hasHeightForWidth())
        self.weight_g_ib.setSizePolicy(sizePolicy)
        self.weight_g_ib.setObjectName("weight_g_ib")
        self.gridLayout_5.addWidget(self.weight_g_ib, 9, 2, 1, 1)
        self.label11_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        self.label11_ib.setObjectName("label11_ib")
        self.gridLayout_5.addWidget(self.label11_ib, 11, 0, 1, 1)
        self.interpreter_ib = QtWidgets.QLabel(self.frame_allinfo_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpreter_ib.sizePolicy().hasHeightForWidth())
        self.interpreter_ib.setSizePolicy(sizePolicy)
        self.interpreter_ib.setObjectName("interpreter_ib")
        self.gridLayout_5.addWidget(self.interpreter_ib, 4, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_allinfo_ib, 1, 1, 1, 2, QtCore.Qt.AlignLeft)
        self.frame_hat_ib = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_hat_ib.sizePolicy().hasHeightForWidth())
        self.frame_hat_ib.setSizePolicy(sizePolicy)
        self.frame_hat_ib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hat_ib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hat_ib.setObjectName("frame_hat_ib")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_hat_ib)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.name_book_ib = QtWidgets.QLabel(self.frame_hat_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_book_ib.sizePolicy().hasHeightForWidth())
        self.name_book_ib.setSizePolicy(sizePolicy)
        self.name_book_ib.setWordWrap(True)
        self.name_book_ib.setObjectName("name_book_ib")
        self.gridLayout_6.addWidget(self.name_book_ib, 2, 0, 1, 1)
        self.author_ib = QtWidgets.QLabel(self.frame_hat_ib)
        self.author_ib.setObjectName("author_ib")
        self.gridLayout_6.addWidget(self.author_ib, 3, 0, 1, 1)
        self.evaluation_ib = QtWidgets.QLabel(self.frame_hat_ib)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evaluation_ib.sizePolicy().hasHeightForWidth())
        self.evaluation_ib.setSizePolicy(sizePolicy)
        self.evaluation_ib.setObjectName("evaluation_ib")
        self.gridLayout_6.addWidget(self.evaluation_ib, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_hat_ib, 0, 1, 1, 1, QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.description_ib = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_ib.sizePolicy().hasHeightForWidth())
        self.description_ib.setSizePolicy(sizePolicy)
        self.description_ib.setWordWrap(True)
        self.description_ib.setObjectName("description_ib")
        self.gridLayout_4.addWidget(self.description_ib, 2, 1, 1, 2, QtCore.Qt.AlignLeft)
        self.img_ib = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_ib.sizePolicy().hasHeightForWidth())
        self.img_ib.setSizePolicy(sizePolicy)
        self.img_ib.setMinimumSize(QtCore.QSize(0, 0))
        self.img_ib.setStyleSheet("")
        self.img_ib.setText("")
        self.img_ib.setPixmap(QtGui.QPixmap(":/newPrefix/icon2/book_shop.png"))
        self.img_ib.setObjectName("img_ib")
        self.gridLayout_4.addWidget(self.img_ib, 0, 0, 2, 1, QtCore.Qt.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_info_book, 2, 2, 1, 1)
        self.frame_personal_data = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_personal_data.sizePolicy().hasHeightForWidth())
        self.frame_personal_data.setSizePolicy(sizePolicy)
        self.frame_personal_data.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_personal_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_personal_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_personal_data.setObjectName("frame_personal_data")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_personal_data)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_save = QtWidgets.QPushButton(self.frame_personal_data)
        self.pushButton_save.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_save.setStyleSheet("QPushButton {\n"
                                           "    background-color: rgb(12, 183, 235);\n"
                                           "    border: none;\n"
                                           "    border-radius: 7px;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(10, 203, 255);\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "    background-color: rgb(9, 145, 182);\n"
                                           "}\n"
                                           "")
        self.pushButton_save.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_13.addWidget(self.pushButton_save, 10, 1, 1, 1, QtCore.Qt.AlignRight | QtCore.Qt.AlignBottom)
        self.frame_state = QtWidgets.QFrame(self.frame_personal_data)
        self.frame_state.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_state.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_state.setObjectName("frame_state")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_state)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_back_pd = QtWidgets.QPushButton(self.frame_state)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_back_pd.sizePolicy().hasHeightForWidth())
        self.pushButton_back_pd.setSizePolicy(sizePolicy)
        self.pushButton_back_pd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_back_pd.setText("")
        self.pushButton_back_pd.setIcon(icon13)
        self.pushButton_back_pd.setIconSize(QtCore.QSize(50, 60))
        self.pushButton_back_pd.setObjectName("pushButton_back_pd")
        self.horizontalLayout_3.addWidget(self.pushButton_back_pd, 0, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(self.frame_state)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.avatar_img_pd = QtWidgets.QLabel(self.frame_state)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatar_img_pd.sizePolicy().hasHeightForWidth())
        self.avatar_img_pd.setSizePolicy(sizePolicy)
        self.avatar_img_pd.setMinimumSize(QtCore.QSize(50, 50))
        self.avatar_img_pd.setMaximumSize(QtCore.QSize(50, 50))
        self.avatar_img_pd.setText("")
        self.avatar_img_pd.setPixmap(QtGui.QPixmap(":/newPrefix/icon2/user.png"))
        self.avatar_img_pd.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar_img_pd.setObjectName("avatar_img_pd")
        self.horizontalLayout_3.addWidget(self.avatar_img_pd, 0, QtCore.Qt.AlignRight)
        self.pushButton_menu_pd = QtWidgets.QPushButton(self.frame_state)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_menu_pd.sizePolicy().hasHeightForWidth())
        self.pushButton_menu_pd.setSizePolicy(sizePolicy)
        self.pushButton_menu_pd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_menu_pd.setText("")
        self.pushButton_menu_pd.setIcon(icon12)
        self.pushButton_menu_pd.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_menu_pd.setObjectName("pushButton_menu_pd")
        self.horizontalLayout_3.addWidget(self.pushButton_menu_pd, 0, QtCore.Qt.AlignRight)
        self.gridLayout_13.addWidget(self.frame_state, 0, 0, 1, 2, QtCore.Qt.AlignTop)
        self.frame_main_pd = QtWidgets.QFrame(self.frame_personal_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main_pd.sizePolicy().hasHeightForWidth())
        self.frame_main_pd.setSizePolicy(sizePolicy)
        self.frame_main_pd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_pd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_pd.setObjectName("frame_main_pd")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_main_pd)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem10 = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem10, 5, 0, 1, 1)
        self.lineEdit_mail = QtWidgets.QLineEdit(self.frame_main_pd)
        self.lineEdit_mail.setReadOnly(True)
        self.lineEdit_mail.setObjectName("lineEdit_mail")
        self.gridLayout_14.addWidget(self.lineEdit_mail, 4, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.comboBox_floor = QtWidgets.QComboBox(self.frame_main_pd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_floor.sizePolicy().hasHeightForWidth())
        self.comboBox_floor.setSizePolicy(sizePolicy)
        self.comboBox_floor.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.comboBox_floor.setObjectName("comboBox_floor")
        self.comboBox_floor.addItem("")
        self.comboBox_floor.addItem("")
        self.comboBox_floor.addItem("")
        self.gridLayout_14.addWidget(self.comboBox_floor, 6, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem11, 7, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_14.addItem(spacerItem12, 2, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame_main_pd)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout_14.addWidget(self.lineEdit_name, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_way_avatar = QtWidgets.QLabel(self.frame_main_pd)
        self.label_way_avatar.setObjectName("label_way_avatar")
        self.gridLayout_14.addWidget(self.label_way_avatar, 9, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QLabel(self.frame_main_pd)
        self.label_3.setObjectName("label_3")
        self.gridLayout_14.addWidget(self.label_3, 8, 0, 1, 1)
        self.pushButton_review = QtWidgets.QPushButton(self.frame_main_pd)
        self.pushButton_review.setObjectName("pushButton_review")
        self.gridLayout_14.addWidget(self.pushButton_review, 8, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.frame_main_pd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_14.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_main_pd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_14.addWidget(self.label_5, 3, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_main_pd, 7, 0, 3, 2)
        self.gridLayout.addWidget(self.frame_personal_data, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Библиотека Читайка"))
        self.label_name_status_mw.setText(_translate("MainWindow", "Библиотека - Читайка"))
        self.pushButton_fold__status_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Свернуть</p></body></html>"))
        self.pushButton_expand_status_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Развернуть</p></body></html>"))
        self.pushButton_close_status_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Закрыть</p></body></html>"))
        self.pushButton_profile_user_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Зайти в акаунт</p></body></html>"))
        self.pushButton_profile_user_mw.setText(_translate("MainWindow", " Пользователь  "))
        self.pushButton_main_menu_mw.setToolTip(_translate("MainWindow",
                                                           "<html><head/><body><p align=\"center\">Перейти на главное</p><p align=\"center\">меню</p></body></html>"))
        self.pushButton_main_menu_mw.setText(_translate("MainWindow", " Главное меню "))
        self.pushButton_setting_user_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Настройка интерфейса</p></body></html>"))
        self.pushButton_setting_user_mw.setText(_translate("MainWindow", " Настройки "))
        self.pushButton_reference_user_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Справка о программе</p></body></html>"))
        self.pushButton_reference_user_mw.setText(_translate("MainWindow", " Справка "))
        self.pushButton_help_user_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Проблема с программой</p></body></html>"))
        self.pushButton_help_user_mw.setText(_translate("MainWindow", " Помощь "))
        self.pushButton_all_bookwark_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Перейти к закладкам</p></body></html>"))
        self.pushButton_all_bookwark_mw.setText(_translate("MainWindow", " Заклаки "))
        self.pushButton_fold_user_mw.setToolTip(_translate("MainWindow",
                                                           "<html><head/><body><p align=\"center\">Скрыть панель пользователя</p></body></html>"))
        self.pushButton_fold_user_mw.setText(_translate("MainWindow", " Скрыть "))
        self.pushButton_exit_user_mw.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Выйти из аккаунта</p></body></html>"))
        self.pushButton_exit_user_mw.setText(_translate("MainWindow", " Выход "))
        self.lineEdit_search_ab.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Строка поиска...</p></body></html>"))
        self.lineEdit_search_ab.setPlaceholderText(_translate("MainWindow", "Введите название книги..."))
        self.pushButton_search.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Поиск книги</p></body></html>"))
        self.pushButton_search.setText(_translate("MainWindow", " Найти "))
        self.pushButton_sort.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Открыть сортировку</p></body></html>"))
        self.pushButton_sort.setText(_translate("MainWindow", " Сортировка "))
        self.pushButton_menu_ab.setToolTip(_translate("MainWindow",
                                                      "<html><head/><body><p align=\"center\">Скрыть/раскрыть меню пользователя</p></body></html>"))
        self.pushButton_close_status_mw_2.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Закрыть</p></body></html>"))
        self.pushButton_search_sort.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Найти по категориям</p></body></html>"))
        self.pushButton_search_sort.setText(_translate("MainWindow", " Искать "))
        self.pushButton_clear.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Очистить категори</p></body></html>"))
        self.pushButton_clear.setText(_translate("MainWindow", " Очистить "))
        self.label_search_author.setText(_translate("MainWindow", "Автор:"))
        self.lineEdit_author.setPlaceholderText(_translate("MainWindow", "Введите автора..."))
        self.label_search_publisher.setText(_translate("MainWindow", "Издательство:"))
        self.lineEdit_publisher.setPlaceholderText(_translate("MainWindow", "Введите издательство..."))
        self.spinBox_from.setPrefix(_translate("MainWindow", "от "))
        self.spinBox_to.setPrefix(_translate("MainWindow", "до "))
        self.label_search_price.setText(_translate("MainWindow", "Цена:"))
        self.dateEdit_second.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.dateEdit_first.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.label_to.setText(_translate("MainWindow", "до"))
        self.label_from.setText(_translate("MainWindow", "от"))
        self.label_date.setText(_translate("MainWindow", "Дата:"))
        self.label_you_mean.setText(_translate("MainWindow", "Возможно вы имели..."))
        self.pushButton_reset.setToolTip(_translate("MainWindow",
                                                    "<html><head/><body><p align=\"center\">Сбросить найденые книги</p></body></html>"))
        self.pushButton_reset.setText(_translate("MainWindow", " Сбросить "))
        self.label.setText(_translate("MainWindow", "Закладки: "))
        self.label_results_bb.setText(_translate("MainWindow", "Итоги:"))
        self.label_price_bb.setText(_translate("MainWindow", "100"))
        self.pushButton_buy_bb.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">Оформить заказ</p></body></html>"))
        self.pushButton_buy_bb.setText(_translate("MainWindow", "Оформить заказ"))
        self.name_user.setText(_translate("MainWindow", "Пользователь"))
        self.pushButton_menu_bb.setToolTip(_translate("MainWindow",
                                                      "<html><head/><body><p align=\"center\">Скрыть/раскрыть меню пользователя</p></body></html>"))
        self.pushButton_menu_ib.setToolTip(_translate("MainWindow",
                                                      "<html><head/><body><p align=\"center\">Скрыть/раскрыть меню пользователя</p></body></html>"))
        self.condition_ib.setText(_translate("MainWindow", "Состояние"))
        self.pushButton_arrange_ib.setText(_translate("MainWindow", "Оформить\n"
                                                                    "   заказ!"))
        self.price_ib.setText(_translate("MainWindow", "Цена"))
        self.age_restrictions_ib.setText(_translate("MainWindow", "TextLabel"))
        self.ISBN_ib.setText(_translate("MainWindow", "TextLabel"))
        self.number_pages_ib.setText(_translate("MainWindow", "TextLabel"))
        self.format_ib.setText(_translate("MainWindow", "TextLabel"))
        self.label5_ib.setText(_translate("MainWindow", "Переводчик"))
        self.publisher_ib.setText(_translate("MainWindow", "TextLabel"))
        self.label3_ib.setText(_translate("MainWindow", "Год издания"))
        self.year_publication_ib.setText(_translate("MainWindow", "TextLabel"))
        self.label8_ib.setText(_translate("MainWindow", "Тип обложки"))
        self.label7_ib.setText(_translate("MainWindow", "Размер"))
        self.label6_ib.setText(_translate("MainWindow", "Количество страниц"))
        self.label1_ib.setText(_translate("MainWindow", "Издательство"))
        self.label10_ib.setText(_translate("MainWindow", "Возрастные ограничения"))
        self.label9_ib.setText(_translate("MainWindow", "Вес, г"))
        self.quantities_ib.setText(_translate("MainWindow", "TextLabel"))
        self.label2_ib.setText(_translate("MainWindow", "Серия"))
        self.series_ib.setText(_translate("MainWindow", "TextLabel"))
        self.label4_ib.setText(_translate("MainWindow", "ISBN"))
        self.cove_type_ib.setText(_translate("MainWindow", "TextLabel"))
        self.weight_g_ib.setText(_translate("MainWindow", "TextLabel"))
        self.label11_ib.setText(_translate("MainWindow", "Количество"))
        self.interpreter_ib.setText(_translate("MainWindow", "TextLabel"))
        self.name_book_ib.setText(_translate("MainWindow", "Name"))
        self.author_ib.setText(_translate("MainWindow", "Автор"))
        self.evaluation_ib.setText(_translate("MainWindow", "Оценка:"))
        self.description_ib.setText(_translate("MainWindow", "Описание"))
        self.pushButton_save.setToolTip(_translate("MainWindow",
                                                   "<html><head/><body><p align=\"center\">Сохранить данные</p><p align=\"center\">пользователя</p></body></html>"))
        self.pushButton_save.setText(_translate("MainWindow", " Сохранить "))
        self.label_2.setText(_translate("MainWindow", "Личные данные"))
        self.pushButton_menu_pd.setToolTip(_translate("MainWindow",
                                                      "<html><head/><body><p align=\"center\">Скрыть/раскрыть меню пользователя</p></body></html>"))
        self.lineEdit_mail.setText(_translate("MainWindow", "Email"))
        self.comboBox_floor.setItemText(0, _translate("MainWindow", "Не указывать"))
        self.comboBox_floor.setItemText(1, _translate("MainWindow", "Мужской"))
        self.comboBox_floor.setItemText(2, _translate("MainWindow", "Женский"))
        self.lineEdit_name.setText(_translate("MainWindow", "Имя"))
        self.label_way_avatar.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Аватарка"))
        self.pushButton_review.setText(_translate("MainWindow", " Обзор "))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Email"))


from Resources import icon_cwt
