# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'помощь.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_assistance(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.466, y1:0.159, x2:0.467, y2:0.972, stop:0 rgba(105, 45, 162, 255), stop:0.502488 rgba(32, 25, 121, 255), stop:1 rgba(105, 45, 162, 255));\n"
"    color: white;\n"
"    font-family: Rubick;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QToolTip {\n"
"    font-family: Rubick;\n"
"    font-size: 12pt;\n"
"    color:white; padding:2px;\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    border-radius:20px;\n"
"    background-color: rgb(30, 33, 61);\n"
"    border: 1px solid white;\n"
"    border-radius: 7px;\n"
"    overflow:hidden;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #54026E;\n"
"    border-radius: 4px;\n"
"    color: rgb(30, 33, 61);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(66, 60, 99);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(28, 28, 28);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 2px solid rrgb(26, 22, 42);\n"
"    background: rgb(66, 60, 99);\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(26, 22, 42);\n"
"    min-width: 22px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    image: url(:/white_icon/icon2/right_arrow (2).png);\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"    image: url(:/white_icon/icon2/left_arrow.png)\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 2px solid rrgb(26, 22, 42);\n"
"    background: rgb(66, 60, 99);\n"
"    width: 15px;\n"
"    width: 18px;\n"
"    margin: 20px 0 20px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(26, 22, 42);;\n"
"    min-width: 22px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    image: url(:/white_icon/icon2/right_arrow (2).png);\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    image: url(:/white_icon/icon2/bot_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    image: url(:/white_icon/icon2/up_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: rgb(66, 60, 99);\n"
"}\n"
"\n"
"QScrollBar::handle:pressed {\n"
"    background-color: rgb(28, 28, 28);\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: rgb(138, 130, 179)\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_status = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_status.sizePolicy().hasHeightForWidth())
        self.frame_status.setSizePolicy(sizePolicy)
        self.frame_status.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status.setObjectName("frame_status")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_status)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_icnon_status = QtWidgets.QLabel(self.frame_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icnon_status.sizePolicy().hasHeightForWidth())
        self.label_icnon_status.setSizePolicy(sizePolicy)
        self.label_icnon_status.setMinimumSize(QtCore.QSize(40, 40))
        self.label_icnon_status.setStyleSheet("image: url(:/newPrefix/icon2/help.png);")
        self.label_icnon_status.setText("")
        self.label_icnon_status.setObjectName("label_icnon_status")
        self.horizontalLayout.addWidget(self.label_icnon_status, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name_status = QtWidgets.QLabel(self.frame_status)
        self.label_name_status.setObjectName("label_name_status")
        self.horizontalLayout.addWidget(self.label_name_status, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_close_status = QtWidgets.QPushButton(self.frame_status)
        self.pushButton_close_status.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_close_status.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton_close_status.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_status.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_status.setIcon(icon1)
        self.pushButton_close_status.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_close_status.setObjectName("pushButton_close_status")
        self.horizontalLayout.addWidget(self.pushButton_close_status, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.frame_status, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_description = QtWidgets.QTextEdit(self.frame)
        self.textEdit_description.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.textEdit_description.setObjectName("textEdit_description")
        self.gridLayout_2.addWidget(self.textEdit_description, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout_2.addWidget(self.lineEdit_name, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.pushButton_review = QtWidgets.QPushButton(self.frame)
        self.pushButton_review.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_review.setObjectName("pushButton_review")
        self.gridLayout_2.addWidget(self.pushButton_review, 5, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_way = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_way.sizePolicy().hasHeightForWidth())
        self.label_way.setSizePolicy(sizePolicy)
        self.label_way.setStyleSheet("font-family: Rubick;\n"
"font-size: 7pt;\n"
"")
        self.label_way.setText("")
        self.label_way.setObjectName("label_way")
        self.gridLayout_2.addWidget(self.label_way, 6, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помощь"))
        self.label_name_status.setText(_translate("MainWindow", "Помощь"))
        self.pushButton_close_status.setToolTip(_translate("MainWindow", "<html><head/><body><p>Закрыть</p></body></html>"))
        self.textEdit_description.setPlaceholderText(_translate("MainWindow", "Опишите подробно вашу проблему..."))
        self.label.setText(_translate("MainWindow", "Заголовок  проблемы/ошибки (обязательно)"))
        self.label_3.setText(_translate("MainWindow", "Картинка ошибки:"))
        self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "Основную тему ошибки..."))
        self.label_2.setText(_translate("MainWindow", "Описание проблемы/ошибки (обязательно)"))
        self.pushButton_review.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Выбрать изображение</p></body></html>"))
        self.pushButton_review.setText(_translate("MainWindow", "Обзор"))
        self.pushButton_send.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Отправить отчет о ошибке</p></body></html>"))
        self.pushButton_send.setText(_translate("MainWindow", "Отправить"))
from Resources import icon_cwt
