# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'уведомление.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notification(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(381, 241)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.515925, y1:0.109, x2:0.496925, y2:0.915, stop:0 rgba(75, 0, 122, 255), stop:0.487562 rgba(123, 20, 142, 255), stop:0.995025 rgba(75, 0, 122, 255));\n"
"    color: white;\n"
"    font-family: Rubick;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    border: 2px solid rgb(221, 153, 255);\n"
"\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QFrame{\n"
"    border: 0px;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QToolTip {\n"
"    font-family: Rubick;\n"
"    font-size: 12pt;\n"
"    color:white; padding:2px;\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    border-radius:20px;\n"
"    background-color: rgb(30, 33, 61);\n"
"    border: 1px solid white;\n"
"    border-radius: 7px;\n"
"    overflow:hidden;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #54026E;\n"
"    border-radius: 4px;\n"
"    color: rgb(30, 33, 61);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(66, 60, 99);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(28, 28, 28);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 2px solid rrgb(26, 22, 42);\n"
"    background: rgb(66, 60, 99);\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(26, 22, 42);\n"
"    min-width: 22px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    image: url(:/white_icon/icon2/right_arrow (2).png);\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"    image: url(:/white_icon/icon2/left_arrow.png)\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 2px solid rrgb(26, 22, 42);\n"
"    background: rgb(66, 60, 99);\n"
"    width: 15px;\n"
"    width: 18px;\n"
"    margin: 20px 0 20px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(26, 22, 42);;\n"
"    min-width: 22px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    image: url(:/white_icon/icon2/right_arrow (2).png);\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    image: url(:/white_icon/icon2/bot_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 2px solid rgb(66, 60, 99);\n"
"    background: rgb(26, 22, 42);\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    image: url(:/white_icon/icon2/up_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: rgb(66, 60, 99);\n"
"}\n"
"\n"
"QScrollBar::handle:pressed {\n"
"    background-color: rgb(28, 28, 28);\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: rgb(138, 130, 179)\n"
"}\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_status = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_status.sizePolicy().hasHeightForWidth())
        self.frame_status.setSizePolicy(sizePolicy)
        self.frame_status.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status.setObjectName("frame_status")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_status)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_icnon_status = QtWidgets.QLabel(self.frame_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icnon_status.sizePolicy().hasHeightForWidth())
        self.label_icnon_status.setSizePolicy(sizePolicy)
        self.label_icnon_status.setMinimumSize(QtCore.QSize(40, 40))
        self.label_icnon_status.setStyleSheet("border-image: url(:/newPrefix/icon2/info.png);")
        self.label_icnon_status.setText("")
        self.label_icnon_status.setObjectName("label_icnon_status")
        self.horizontalLayout.addWidget(self.label_icnon_status, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name_status = QtWidgets.QLabel(self.frame_status)
        self.label_name_status.setObjectName("label_name_status")
        self.horizontalLayout.addWidget(self.label_name_status, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_close_status = QtWidgets.QPushButton(self.frame_status)
        self.pushButton_close_status.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_close_status.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton_close_status.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_status.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon2/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close_status.setIcon(icon1)
        self.pushButton_close_status.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_close_status.setObjectName("pushButton_close_status")
        self.horizontalLayout.addWidget(self.pushButton_close_status, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_status, 0, QtCore.Qt.AlignTop)
        self.frame_main = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main.sizePolicy().hasHeightForWidth())
        self.frame_main.setSizePolicy(sizePolicy)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_main)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.frame_main)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.frame_main)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Уведомление"))
        self.label_name_status.setText(_translate("Dialog", "Уведомление"))
        self.pushButton_close_status.setToolTip(_translate("Dialog", "<html><head/><body><p>Закрыть</p></body></html>"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_ok.setText(_translate("Dialog", "Ok"))
from Resources import icon_cwt
